steps:


- id: "centrifugo_cluster"
  name: hashicorp/terraform:1.3.9
  entrypoint: sh
  args: 
  - "-c"
  - |
      cd staging/terraform/test
      terraform init
      terraform plan


timeout: 2400s
