steps:
- id: "terraform"
  name: hashicorp/terraform:1.3.9
  entrypoint: sh
  args: 
  - "-c"
  - |
      terraform init -var-file=staging.tfvars
      terraform plan -var-file=staging.tfvars
      terraform apply -auto-approve -var-file=staging.tfvars

timeout: 2400s
