apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      creationTimestamp: null
      labels:
        app: prometheus
    spec:
      containers:
      - command:
        - prometheus
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/data
        - --storage.tsdb.retention=5m
        image: prom/prometheus:v2.19.0
        imagePullPolicy: IfNotPresent
        name: prometheus
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config
          subPath: prometheus.yml
        - mountPath: /data
          name: data-volume
      - args:
        - --stackdriver.project-id
        - smartcart-stagingization
        - --stackdriver.kubernetes.cluster-name
        - {{ .Values.cluster_name }}
        - --stackdriver.kubernetes.location
        - asia-northeast1
        - --prometheus.wal-directory
        - /data/wal
        - --prometheus.api-address
        - http://127.0.0.1:9090
        - --include
        - '{__name__=~"echo_requests_total",job="kubernetes-pods"}'
        - --include
        - '{__name__=~"port_.*",job="kubernetes-service-endpoints"}'
        image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.7.3
        imagePullPolicy: IfNotPresent
        name: sidecar
        ports:
        - containerPort: 9091
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: prometheus
      serviceAccountName: prometheus
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: prometheus.yml
            mode: 420
            path: prometheus.yml
          name: prometheus-config
        name: prometheus-config
      - emptyDir: {}
        name: data-volume
