steps:

- id: "manju_cluster"
  name: hashicorp/terraform:1.3.9
  entrypoint: sh
  args: 
  - "-c"
  - |
      cd production/terraform/manju
      terraform init
      terraform plan



# - id: "centrifugo_cluster"
#   name: hashicorp/terraform:1.3.9
#   entrypoint: sh
#   args: 
#   - "-c"
#   - |
#       cd production/terraform/centrifugo
#       terraform init
#       terraform plan



# - id: "centrifugo_cluster"
#   name: hashicorp/terraform:1.3.9
#   entrypoint: sh
#   args: 
#   - "-c"
#   - |
#       cd production/terraform/yakiimo
#       terraform init
#       terraform plan



# - id: "centrifugo_cluster"
#   name: hashicorp/terraform:1.3.9
#   entrypoint: sh
#   args: 
#   - "-c"
#   - |
#       cd production/terraform/test
#       terraform init
#       terraform plan


timeout: 2400s
